### DISCUSSION TITLE
Release v0.23.0

### DISCUSSION THREAD

**Discussion by gianlucam76** [projectsveltos/addon-controller#454] [Announcements]
🚀 Features:

- Allows Sveltos to get YAMLs/JSONs from flux sources

**Comment by gianlucam76** [comment]
Sveltos can now use Flux sources to get YAML/JSON that needs to be deployed in matching clusters.

For instance Flux is used to sync the content of this [repo]( https://github.com/gianlucam76/yaml_flux.git) on the management cluster:

```yaml 
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  creationTimestamp: "2024-02-07T13:53:12Z"
  finalizers:
  - finalizers.fluxcd.io
  generation: 1
  labels:
    kustomize.toolkit.fluxcd.io/name: flux-system
    kustomize.toolkit.fluxcd.io/namespace: flux-system
  name: flux-system
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  secretRef:
    name: flux-system
  timeout: 60s
  url: https://github.com/gianlucam76/yaml_flux.git
```

Then a Sveltos ClusterProfile can references the GitRepository and take and deploy content in the kyverno directory

```yaml
apiVersion: config.projectsveltos.io/v1alpha1
kind: ClusterProfile
metadata:
  name: deploy-kyverno-resources
spec:
  clusterSelector: env=fv
  policyRefs:
  - kind: GitRepository
    name: flux-system
    namespace: flux-system
    path: kyverno
```
    
    
All resources are deployed in any matching cluster.
For instance looking at the Status of a ClusterSummary

```yaml
  status:
    dependencies: no dependencies
    featureSummaries:
    - deployedGroupVersionKind:
      - ServiceAccount.v1.
      - ConfigMap.v1.
      - CustomResourceDefinition.v1.apiextensions.k8s.io
      - ClusterRole.v1.rbac.authorization.k8s.io
      - ClusterRoleBinding.v1.rbac.authorization.k8s.io
      - Role.v1.rbac.authorization.k8s.io
      - RoleBinding.v1.rbac.authorization.k8s.io
      - Service.v1.
      - Deployment.v1.apps
      - CronJob.v1.batch
      - Pod.v1.
      - Job.v1.batch
      featureID: Resources
      hash: W1QN55ythh6NfmAg+jPLYUOrKIczEvot5Z2vIBa+V2E=
      lastAppliedTime: "2024-02-07T13:55:14Z"
      status: Provisioned
```

The content of the GitRepository/Bucket can be a template as well.
If the GitRepository instance referenced above by ClusterProfile has the annotation "projectsveltos.io/template" Sveltos will take the content of all the files and instantiate those using data from resources in the management cluster. So exactly same behaviour currently existing with referenced Secret and ConfigMap.
