### DISCUSSION TITLE
What is the order of precedence in case of conflicting ClusterProfiles?

### DISCUSSION THREAD

**Discussion by rbjorklin** [projectsveltos/addon-controller#539] [Q&A] [answered]
Say I have a base set of components I want applied to all my clusters:
```yaml
apiVersion: config.projectsveltos.io/v1alpha1
kind: ClusterProfile
metadata:
  name: base-components
spec:
  clusterSelector: env=dev
  syncMode: Continuous
  helmCharts:
  - repositoryURL: https://open-policy-agent.github.io/gatekeeper/charts
    repositoryName: gatekeeper
    chartName: gatekeeper/gatekeeper
    chartVersion:  3.9.0
    releaseName: gatekeeper
    releaseNamespace: gatekeeper
    helmChartAction: Install
  - chartName: kyverno/kyverno
    chartVersion: v3.0.1
    helmChartAction: Install
    releaseName: kyverno-latest
    releaseNamespace: kyverno
    repositoryName: kyverno
    repositoryURL: https://kyverno.github.io/kyverno/
```

and now I want to upgrade one of the components in this set so I create an override:
```yaml
apiVersion: config.projectsveltos.io/v1alpha1
kind: ClusterProfile
metadata:
  name: gatekeeper-override
spec:
  clusterSelector: cluster=dev-1
  syncMode: Continuous
  helmCharts:
  - repositoryURL: https://open-policy-agent.github.io/gatekeeper/charts
    repositoryName: gatekeeper
    chartName: gatekeeper/gatekeeper
    chartVersion:  3.10.0
    releaseName: gatekeeper
    releaseNamespace: gatekeeper
    helmChartAction: Install
```

Is there an order of precedence here? If so how is it determined?

EDIT: There is a chance I can solve this with: https://github.com/projectsveltos/addon-controller/issues/532

**Comment by gianlucam76** [comment]
In your example, the second ClusterProfile gatekeeper-override won't be deployed. 

An Helm chart (in a given managed cluster) can only be managed by a ClusterProfile. So you will see in the ClusterSummary corresponding to your second ClusterProfile a status like:

```
  helmReleaseSummaries:
  - conflictMessage: ClusterSummary base-components-capi-clusterapi-workload managing
      it
    releaseName: gatekeeper
    releaseNamespace: gatekeeper
    status: Conflict
```

In general, the order is this:

1.  all helm charts listed in a ClusterProfile are deployed in the very same order. So looking at your first ClusterProfile, gatekeeper will be deployed before Kyverno (this is covered  with more details [here](https://projectsveltos.github.io/sveltos/deployment_order/manifest_order/)

2. A ClusterProfile might depend on another ClusterProfile. Let's say you have two ClusterProfiles (kyverno and prometheus). And you want to install Kyverno before prometheus is deployed

```yaml
apiVersion: config.projectsveltos.io/v1alpha1
kind: ClusterProfile 
metadata: 
  name: prometheus
spec:
  dependsOn:
  - kyverno  # name of the ClusterProfile that must be deployed before this is deployed
```

This is covered in more details [here](https://projectsveltos.github.io/sveltos/deployment_order/depends_on/)

**Comment by gianlucam76** [comment]
and if you want to upgrade gatekeeper, you can simply change the version in your first clusterProfile. Though this will upgrade all clusters in your set. 

```yaml
apiVersion: config.projectsveltos.io/v1alpha1
kind: ClusterProfile
metadata:
  name: base-components
spec:
  clusterSelector: env=dev
  syncMode: Continuous
  helmCharts:
  - repositoryURL: https://open-policy-agent.github.io/gatekeeper/charts
    repositoryName: gatekeeper
    chartName: gatekeeper/gatekeeper
    chartVersion:  3.16.0 # changing the version will instruct Sveltos to upgrade (or downgrade)
    releaseName: gatekeeper
    releaseNamespace: gatekeeper
    helmChartAction: Install
  - chartName: kyverno/kyverno
    chartVersion: v3.0.1
    helmChartAction: Install
    releaseName: kyverno-latest
    releaseNamespace: kyverno
    repositoryName: kyverno
    repositoryURL: https://kyverno.github.io/kyverno/
```

If you want to update only one cluster to see all works just fine, you can use the maxUpdate field of the ClusterProfile along with ValidateHealths. What Sveltos will do in that case, it will trigger the upgrade only on one cluster and only when all is successful will move to next cluster

```
 maxUpdate: 1
```

This is covered [here](https://projectsveltos.github.io/sveltos/addons/rolling_update_strategy/)

At the moment there is no way to say this ClusterProfile takes it over for this helm charts. The easiest would probably be what you mentioned (to express the Kustomize Path as a template so different paths are used for different clusters matching same ClusterProfile).
