### DISCUSSION TITLE
Release v0.36.0

### DISCUSSION THREAD

**Discussion by gianlucam76** [projectsveltos/addon-controller#668] [Announcements]
## 🚀 Features:

- Introduce ability to pause/unpause a cluster: SveltosCluster has a new field called `Schedule` that allows
to specify when to unpause a cluster. A Paused SveltosCluster will receive no update from Sveltos.
This feature so enable having a maintanence window on each managed cluster. Only during this maintanance window, update will be delivered to cluster. For instance, following will have the SveltosCluster set to unpaused only from Friday, 8PM
to Monday 7AM every week:

```yaml
apiVersion: [lib.projectsveltos.io/v1beta1](http://lib.projectsveltos.io/v1beta1)
kind: SveltosCluster
metadata:
  name: cluster1
  namespace: civo
spec:
  activeWindow:
    from: 0 20 * * 5  # Friday 8PM (0 hour, 20th minute, any day of month, any month, Friday)
    to: 0 7 * * 1    # Monday 7AM (0 hour, 7th minute, any day of month, any month, Monday)
```

- When creating a Profile/ClusterProfile with syncMode set to `ContinuosWithDriftDetection`, adds ability to specify a set
of fields, for certain resources, to be ignored when evaluation configuration drift. More [here](https://github.com/projectsveltos/addon-controller/commits/dev/). For instance following will have Sveltos ignore changes in `Replicas` field for any deployment 

```yaml
apiVersion: [config.projectsveltos.io/v1beta1](http://config.projectsveltos.io/v1beta1)
kind: ClusterProfile
metadata:
  name: nginx
spec:
  clusterSelector:
    matchLabels:
      env: prod
  syncMode: ContinuousWithDriftDetection
  helmCharts:
  - repositoryURL:    https://helm.nginx.com/stable/
    repositoryName:   nginx-stable
    chartName:        nginx-stable/nginx-ingress
    chartVersion:     1.3.1
    releaseName:      nginx-latest
    releaseNamespace: nginx
    helmChartAction:  Install
  driftExclusions:
  - paths:
    - "/spec/replicas"
    target:
      kind: Deployment
```

- ability to patch sub resources: referenced ConfigMaps/Secrets/Flux Sources with `projectsveltos.io/subresources` set indicates Sveltos to patch sub resources. This is achieved by leveraging the `projectsveltos.io/subresources` annotation. When this annotation is present on a resource referenced in the PolicyRefs section, Sveltos will update the designated subresources alongside the main resource. Subresources are specified as a comma-separated list within the annotation value.

## 🌱 Others
- Bump clusterAPI to v1.8.1
- Bump golang to v1.22.5
