### DISCUSSION TITLE
Can Project Sveltos self-manage?

### DISCUSSION THREAD

**Discussion by rbjorklin** [projectsveltos/addon-controller#694] [Q&A]
Say I want to make sure my project sveltos deployment always mirrors what is in a git repository. Is it safe to create a ClusterProfile to apply project sveltos to a management cluster?

**Comment by gianlucam76** [comment]
Hi @rbjorklin yes. You can do that. I usually start with a kind cluster where I deploy Sveltos. Then create my management cluster (usually using Civo). Register this cluster with Sveltos in the kind cluster. Then deploy Sveltos there so I can kill my Kind cluster and use my Civo cluster as my new management cluster.

In other words, if you have a managed cluster that you want to transform in your new management cluster, you can use a ClusterProfile to deploy Sveltos into such a managed cluster. After that succeeds, that managed cluster becomes your new management cluster.

```yaml
apiVersion: config.projectsveltos.io/v1beta1
kind: ClusterProfile
metadata:
  name: projectsveltos
spec:
  clusterSelector:
    matchLabels:
      env: fv
  syncMode: Continuous
  helmCharts:
  - repositoryURL:    oci://registry-1.docker.io/gianlucam76
    repositoryName:   projectsveltos
    chartName:        projectsveltos
    chartVersion:     0.38.1
    releaseName:      projectsveltos
    releaseNamespace: projectsveltos
    helmChartAction:  Install
    registryCredentialsConfig:
      credentials:
        name: regcred
        namespace: default
```

keep in mind that Sveltos requires cert-manager in the management cluster. So if you don't have that, you can add it

```yaml
apiVersion: config.projectsveltos.io/v1beta1
kind: ClusterProfile
metadata:
  name: projectsveltos
spec:
  clusterSelector:
    matchLabels:
      env: fv
  syncMode: Continuous
  helmCharts:
  - repositoryURL:    https://charts.jetstack.io
    repositoryName:   jetstack
    chartName:        jetstack/cert-manager
    chartVersion:     v1.15.3
    releaseName:      cert-manager
    releaseNamespace: cert-manager
    helmChartAction:  Install
  - repositoryURL:    oci://registry-1.docker.io/gianlucam76
    repositoryName:   projectsveltos
    chartName:        projectsveltos
    chartVersion:     0.38.1
    releaseName:      projectsveltos
    releaseNamespace: projectsveltos
    helmChartAction:  Install
    registryCredentialsConfig:
      credentials:
        name: regcred
        namespace: default
```

**Comment by rbjorklin** [comment]
I've tried this and ended up in a bad state where Project Sveltos effectively deletes all the resources in my cluster. I think what happened was that I introduced a mistake in my `kustomization.yaml` where I was referencing a file that no longer existed which seems to have caused a deletion of all the resources when the apply failed.

**Comment by gianlucam76** [comment]
Thanks @rbjorklin I will give this a try again on Monday. Thanks

**Comment by gianlucam76** [comment]
Hi @rbjorklin this is what I did:

1. created a kind cluster on my laptop and deployed projectsveltos
2. created a Civo cluster (mgmt-cluser) and registered to be managed by Sveltos (deployed in the kind cluster).
3. Deployed Sveltos to the Civo cluster from the kind cluster

This is how I deployed projectsveltos from the kind cluster to the Civo cluster.

```yaml
apiVersion: config.projectsveltos.io/v1beta1
kind: ClusterProfile
metadata:
  name: deploy-cert-manager
spec:
  clusterSelector:
    matchLabels:
      env: mgmt
  syncMode: Continuous
  helmCharts:
  - repositoryURL:    https://charts.jetstack.io
    repositoryName:   jetstack
    chartName:        jetstack/cert-manager
    chartVersion:     v1.16.0
    releaseName:      cert-manager
    releaseNamespace: cert-manager
    helmChartAction:  Install
    values: |
      crds:
        enabled: true
```

```yaml
apiVersion: config.projectsveltos.io/v1beta1
kind: ClusterProfile
metadata:
  name: deploy-projectsveltos
spec:
  clusterSelector:
    matchLabels:
      env: mgmt
  dependsOn:
  - deploy-cert-manager
  syncMode: Continuous
  helmCharts:
  - repositoryURL:    https://projectsveltos.github.io/helm-charts
    repositoryName:   projectsveltos
    chartName:        projectsveltos/projectsveltos
    chartVersion:     v0.38.4
    releaseName:      projectsveltos
    releaseNamespace: projectsveltos
    helmChartAction:  Install
```

```sveltosctl show addons                                  
+-------------------+---------------+----------------+----------------+---------+--------------------------------+--------------------------------------+
|      CLUSTER      | RESOURCE TYPE |   NAMESPACE    |      NAME      | VERSION |              TIME              |               PROFILES               |
+-------------------+---------------+----------------+----------------+---------+--------------------------------+--------------------------------------+
| civo-mgmt/cluster | helm chart    | projectsveltos | projectsveltos | 0.38.4  | 2024-10-08 14:20:49 +0200 CEST | ClusterProfile/deploy-projectsveltos |
| civo-mgmt/cluster | helm chart    | cert-manager   | cert-manager   | v1.16.0 | 2024-10-08 14:16:54 +0200 CEST | ClusterProfile/deploy-cert-manager   |
+-------------------+---------------+----------------+----------------+---------+--------------------------------+--------------------------------------+
```

In this state I created another Civo cluster and registered it to be managed by Sveltos running in the other Civo cluster. And deployed Kyverno

```
sveltosctl show addons
+--------------+---------------+-----------+----------------+---------+--------------------------------+-------------------------------+
|   CLUSTER    | RESOURCE TYPE | NAMESPACE |      NAME      | VERSION |              TIME              |           PROFILES            |
+--------------+---------------+-----------+----------------+---------+--------------------------------+-------------------------------+
| civo/cluster | helm chart    | kyverno   | kyverno-latest | 3.2.6   | 2024-10-08 14:24:33 +0200 CEST | ClusterProfile/deploy-kyverno |
+--------------+---------------+-----------+----------------+---------+--------------------------------+-------------------------------+
```

while in this state I triggered Sveltos upgrade from v0.38.4 to v0.39.0 by changing the ClusterProfile __deploy-projectsveltos__ in the kind cluster. Sveltos upgrade went through without removing anything.


PS: You might see projectsveltos deployment fail due to 

```
failureMessage: "post-upgrade hooks failed: warning: Hook post-upgrade projectsveltos/templates/default-classifier.yaml
        failed: 1 error occurred:\n\t* classifiers.lib.projectsveltos.io \"default-classifier\"
```

while pointing to the civo mgmt cluster just issue 
kubectl delete classifier  default-classifier

I will fix this in next release
