### ISSUE TITLE
BUG: EventSource, "Resource" Template variable

### ISSUE THREAD

**Issue by Banh-Canh** [projectsveltos/addon-controller#1043]
# Problem Description

Hello, I'm trying to access child cluster resource spec so I can use some of its value in a resource I want to deploy in the cluster MGMT.
To achieve that, i'm using EventSource / EventTrigger combo with the following specs:

```yaml
apiVersion: lib.projectsveltos.io/v1beta1
kind: EventSource
metadata:
  name: loadbalancer-class-handler
spec:
  collectResources: true
  resourceSelectors:
    - group: ''
      version: 'v1'
      kind: 'Service'
      evaluate: |
        function evaluate()
          hs = {}
          hs.matching = false
          if obj.spec.type == "LoadBalancer" then
            hs.matching = true
            return hs
          end
          return hs
        end
---
apiVersion: lib.projectsveltos.io/v1beta1
kind: EventTrigger
metadata:
  name: loadbalancer-class-handler
spec:
  sourceClusterSelector:
    matchLabels:
      topology.cluster.x-k8s.io/owned: ''
  eventSourceName: loadbalancer-class-handler
  syncMode: ContinuousWithDriftDetection
  oneForEvent: true
  policyRefs:
    - kind: ConfigMap
      name: loadbalancer-class-handler-svc
      namespace: projectsveltos
      deploymentType: Local
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: loadbalancer-class-handler-svc
  annotations:
    projectsveltos.io/template: 'true'
data:
  service.yaml: |
    kind: Service
    apiVersion: v1
    metadata:
      name: "lb-{{ .Resource.metadata.name }}-{{ .Resource.metadata.namespace }}-{{ .Cluster.metadata.name }}"
      namespace: projectsveltos
      annotations:
        lb.bealv.io/name: "{{ .Resource.metadata.name }}"
        lb.bealv.io/namespace: "{{ .Resource.metadata.namespace }}"
    spec:
      ports:
        {{- range $port := .Resource.spec.ports }}
        - name: "{{ $port.name }}"
          port: {{ $port.port }}
          protocol: "{{ $port.protocol }}"
          targetPort: {{ $port.nodePort }}
        {{- end }}
      selector:
          cluster.x-k8s.io/cluster-name: "{{ .Cluster.metadata.name }}"
      type: LoadBalancer
---
```

This is basically the example in : https://projectsveltos.github.io/sveltos/events/example_loadbalancer/

but I can't make it work. It looks like I can't access the {{ .Resource }} variable. Can I get any help regarding how to access these "remote" values ?

# System Information

_INSTRUCTIONS: Provide the system and application information below._

CLUSTERAPI VERSION: `v1.8.4 `
SVELTOS VERSION: ` v0.48.0`
KUBERNETES VERSION: ` v1.32.1`

# Logs

The related clustersummary status:
```yaml
status:
  dependencies: no dependencies
  featureSummaries:
  - failureMessage: 'error executing template "{{ range $resource := .Resources }}\nkind:
      Service\napiVersion: v1\nmetadata:\n  name: \"lb-{{ $resource.metadata.name
      }}-{{ $resource.metadata.namespace }}-{{ .Cluster.metadata.name }}\"\n  namespace:
      projectsveltos\n  annotations:\n    lb.bealv.io/name: \"{{ $resource.metadata.name
      }}\"\n    lb.bealv.io/namespace: \"{{ $resource.metadata.namespace }}\"\nspec:\n  ports:\n    {{-
      range $port := $resource.spec.ports }}\n    - name: \"{{ $port.name }}\"\n      port:
      {{ $port.port }}\n      protocol: \"{{ $port.protocol }}\"\n      targetPort:
      {{ $port.nodePort }}\n    {{- end }}\n  selector:\n      cluster.x-k8s.io/cluster-name:
      \"{{ .Cluster.metadata.name }}\"\n  type: LoadBalancer\n{{ end }}\n": template:
      capi-system-bealv-test-sveltos-hrovq0u0sy7iv2hokyym-capi-bealv-test:1:22: executing
      "capi-system-bealv-test-sveltos-hrovq0u0sy7iv2hokyym-capi-bealv-test" at <.Resources>:
      can''t evaluate field Resources in type *controllers.currentClusterObjects'
    featureID: Resources
    hash: 7sht9IRXNRaEJYjpyoLIhpp4+Bm5pJxu8Kq6mP6MYYE=
    lastAppliedTime: "2025-02-18T22:21:54Z"
    status: Provisioning
```

and the EventReport which see the resources that triggered the event:
```yaml
apiVersion: lib.projectsveltos.io/v1beta1
kind: EventReport
metadata:
  labels:
    eventreport.projectsveltos.io/cluster-name: bealv-test
    eventreport.projectsveltos.io/cluster-type: capi
    projectsveltos.io/eventsource-name: loadbalancer-class-handler
  name: capi--loadbalancer-class-handler--bealv-test
  namespace: capi-system
spec:
  clusterName: bealv-test
  clusterNamespace: capi-system
  clusterType: Capi
  eventSourceName: loadbalancer-class-handler
  matchingResources:
  - apiVersion: v1
    kind: Service
    name: envoy
    namespace: ingress-contour
  resources: eyJhcGlWZXJzaW9uIjoidjEiLCJraW5kIjoiU2VydmljZSIsIm1ldGFkYXRhIjp7ImFubm90YXRpb25zIjp7InByb2plY3RzdmVsdG9zLmlvL2hhc2giOiJzaGEyNTY6NDg0NTVjMjQyMWMyMTM2ZDI3NTAwYjIwYzZlNTg1ZWU3YzMzYzFjNTA0OTYwZWE3NDk3N2Y4ZDAzYjgzNjk5MCIsInByb2plY3RzdmVsdG9zLmlvL293bmVyLXRpZXIiOiIxMDAiLCJzZXJ2aWNlLmJldGEua3ViZXJuZXRlcy5pby9hd3MtbG9hZC1iYWxhbmNlci1iYWNrZW5kLXByb3RvY29sIjoidGNwIn0sImNyZWF0aW9uVGltZXN0YW1wIjoiMjAyNS0wMi0xOFQxODozNTowN1oiLCJsYWJlbHMiOnsicHJvamVjdHN2ZWx0b3MuaW8vcmVhc29uIjoiS3VzdG9taXplIiwicHJvamVjdHN2ZWx0b3MuaW8vcmVmZXJlbmNlLWtpbmQiOiJHaXRSZXBvc2l0b3J5IiwicHJvamVjdHN2ZWx0b3MuaW8vcmVmZXJlbmNlLW5hbWUiOiJpbmZyYSIsInByb2plY3RzdmVsdG9zLmlvL3JlZmVyZW5jZS1uYW1lc3BhY2UiOiJmbHV4LXN5c3RlbSJ9LCJtYW5hZ2VkRmllbGRzIjpbeyJhcGlWZXJzaW9uIjoidjEiLCJmaWVsZHNUeXBlIjoiRmllbGRzVjEiLCJmaWVsZHNWMSI6eyJmOm1ldGFkYXRhIjp7ImY6YW5ub3RhdGlvbnMiOnsiZjpwcm9qZWN0c3ZlbHRvcy5pby9oYXNoIjp7fSwiZjpwcm9qZWN0c3ZlbHRvcy5pby9vd25lci10aWVyIjp7fSwiZjpzZXJ2aWNlLmJldGEua3ViZXJuZXRlcy5pby9hd3MtbG9hZC1iYWxhbmNlci1iYWNrZW5kLXByb3RvY29sIjp7fX0sImY6bGFiZWxzIjp7ImY6cHJvamVjdHN2ZWx0b3MuaW8vcmVhc29uIjp7fSwiZjpwcm9qZWN0c3ZlbHRvcy5pby9yZWZlcmVuY2Uta2luZCI6e30sImY6cHJvamVjdHN2ZWx0b3MuaW8vcmVmZXJlbmNlLW5hbWUiOnt9LCJmOnByb2plY3RzdmVsdG9zLmlvL3JlZmVyZW5jZS1uYW1lc3BhY2UiOnt9fSwiZjpvd25lclJlZmVyZW5jZXMiOnsiazp7XCJ1aWRcIjpcIjI4ZGY4YTQxLWMzNzctNDczMC1iYWVlLThmOTM1MWYwZmU4NVwifSI6e319fSwiZjpzcGVjIjp7ImY6ZXh0ZXJuYWxUcmFmZmljUG9saWN5Ijp7fSwiZjpwb3J0cyI6eyJrOntcInBvcnRcIjo0NDMsXCJwcm90b2NvbFwiOlwiVENQXCJ9Ijp7Ii4iOnt9LCJmOm5hbWUiOnt9LCJmOnBvcnQiOnt9LCJmOnByb3RvY29sIjp7fSwiZjp0YXJnZXRQb3J0Ijp7fX0sIms6e1wicG9ydFwiOjgwLFwicHJvdG9jb2xcIjpcIlRDUFwifSI6eyIuIjp7fSwiZjpuYW1lIjp7fSwiZjpwb3J0Ijp7fSwiZjpwcm90b2NvbCI6e30sImY6dGFyZ2V0UG9ydCI6e319fSwiZjpzZWxlY3RvciI6e30sImY6dHlwZSI6e319fSwibWFuYWdlciI6ImFwcGxpY2F0aW9uL2FwcGx5LXBhdGNoIiwib3BlcmF0aW9uIjoiQXBwbHkiLCJ0aW1lIjoiMjAyNS0wMi0xOFQxODozNTowN1oifV0sIm5hbWUiOiJlbnZveSIsIm5hbWVzcGFjZSI6ImluZ3Jlc3MtY29udG91ciIsIm93bmVyUmVmZXJlbmNlcyI6W3siYXBpVmVyc2lvbiI6ImNvbmZpZy5wcm9qZWN0c3ZlbHRvcy5pby92MWJldGExIiwia2luZCI6IkNsdXN0ZXJQcm9maWxlIiwibmFtZSI6ImluZ3Jlc3MtY29udHJvbGxlciIsInVpZCI6IjI4ZGY4YTQxLWMzNzctNDczMC1iYWVlLThmOTM1MWYwZmU4NSJ9XSwicmVzb3VyY2VWZXJzaW9uIjoiMTAxNzE0IiwidWlkIjoiNThiYTkzNzgtMjYzMC00NGU4LWIyMTQtYmE0YTZlY2Q2OGQ4In0sInNwZWMiOnsiYWxsb2NhdGVMb2FkQmFsYW5jZXJOb2RlUG9ydHMiOnRydWUsImNsdXN0ZXJJUCI6IjE3Mi4xNy4xNDAuMjIyIiwiY2x1c3RlcklQcyI6WyIxNzIuMTcuMTQwLjIyMiJdLCJleHRlcm5hbFRyYWZmaWNQb2xpY3kiOiJMb2NhbCIsImhlYWx0aENoZWNrTm9kZVBvcnQiOjMwMjAxLCJpbnRlcm5hbFRyYWZmaWNQb2xpY3kiOiJDbHVzdGVyIiwiaXBGYW1pbGllcyI6WyJJUHY0Il0sImlwRmFtaWx5UG9saWN5IjoiU2luZ2xlU3RhY2siLCJwb3J0cyI6W3sibmFtZSI6Imh0dHAiLCJub2RlUG9ydCI6MzI0MjcsInBvcnQiOjgwLCJwcm90b2NvbCI6IlRDUCIsInRhcmdldFBvcnQiOjgwODB9LHsibmFtZSI6Imh0dHBzIiwibm9kZVBvcnQiOjMyNjA1LCJwb3J0Ijo0NDMsInByb3RvY29sIjoiVENQIiwidGFyZ2V0UG9ydCI6ODQ0M31dLCJzZWxlY3RvciI6eyJhcHAiOiJlbnZveSJ9LCJzZXNzaW9uQWZmaW5pdHkiOiJOb25lIiwidHlwZSI6IkxvYWRCYWxhbmNlciJ9LCJzdGF0dXMiOnsibG9hZEJhbGFuY2VyIjp7fX19Ci0tLQ==
```

**Comment by gianlucam76** [comment]
The error is in the referenced ConfigMap. Since the ConfigMap is being instantiated in response to an event (so using the .Resource) the annotation must be projectsveltos.io/instantiate: 'true' (you had projectsveltos.io/template: 'true' but that annotation is only used by ClusterProfile when instantiating template using information present in the management cluster, not events). Apologies if this error is also present in the documentation  (will fix that in case).

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: loadbalancer-class-handler-svc
  annotations:
    projectsveltos.io/instantiate: 'true'
```

One extra note since you are using  **deploymentType: Local** please remember to [grant the extra permission](https://projectsveltos.github.io/sveltos/events/db-as-a-service-multiple-db-per-cluster/#granting-extra-rbac) to Sveltos so it can create Secrets in the management cluster.
