### ISSUE TITLE
Document CustomResources ownership

### ISSUE THREAD

**Issue by gianlucam76** [projectsveltos/addon-controller#117]
User Story

As a developer I would like comprehensive documentation for the CRs ownership relationship. For instance, when a cluster matches a ClusterProfile, a ClusterSummary is created and it is owned by the ClusterProfile instance.
This comes in particularly handy as the number of CRDs of the project keeps growing.

Detailed Description

In order to make it easier for devs to quickly understand sveltos internals, in the documentation (https://projectsveltos.github.io/sveltos/) create a section with some CRs ownership diagram.
Add information on when CRs are created/update/deleted and which other CR owns it.

/kind documentation
/help
/good-first-issue

**Comment by hanshal101** [comment]
Hey @gianlucam76 I would like to work on this issue.
I had a doubt where should I write the documentation for the CRs?

**Comment by gianlucam76** [comment]
@hanshal101  thank you so much. The repository used for documentation is [sveltos](https://github.com/projectsveltos/sveltos)

We use mkdocs behind the scene. So once you fork/clone repo locally, if you have mkdocs installed, "mkdocs serve" will allow you see change locally

**Comment by hanshal101** [comment]
Gotcha
Should I make a separate section in the /docs/CRs Ownership.

**Comment by gianlucam76** [comment]
New section sounds good. Thank you

**Comment by hanshal101** [comment]
Ok Thanks for the swift response

**Comment by hanshal101** [comment]
Heyy @gianlucam76 I have made this diagram according to my understanding related to this issue. Please guide me for all the changes that is to be made for this diagram.
Also I made this according to the ClusterProfile and ClusterSummary, while when the Profile makes the add-ons on the cluster the metadata is created (here you can see the table).
![image](https://github.com/projectsveltos/addon-controller/assets/122217807/cafa4cea-9825-4e14-b017-ce928fc0f565)

Thank You.

**Comment by gianlucam76** [comment]
Thank you @hanshal101 !!! 

You are correct, ClusterProfile owns ClusterSummary.

ClusterProfile.Spec.ClusterSelector contains a Kubernetes label selector used by Sveltos to decide on which clusters to deploy add-ons (helm charts, raw YAML, etc) listed in the ClusterProfile instance.

For every cluster matching a ClusterProfile, a ClusterSummary is created:
- ClusterSummary owner is the ClusterProfile creating it (ClusterSummary ownerReferences contains that information)
- ClusterSummary also contains labels indicating which cluster (in the example below the labels projectsveltos.io/cluster-type and  projectsveltos.io/cluster-name indicates that the cluster is a ClusterAPI powered cluster named clusterapi-workload)
- ClusterSummary is created in the managed cluster namespace (while ClusterProfile is a cluster wide resource)


```yaml
apiVersion: config.projectsveltos.io/v1alpha1
kind: ClusterSummary
metadata:
  ...
  labels:
    projectsveltos.io/cluster-name: clusterapi-workload
    projectsveltos.io/cluster-profile-name: kyverno
    projectsveltos.io/cluster-type: Capi
  name: kyverno-capi-clusterapi-workload
  namespace: default
  ownerReferences:
  - apiVersion: config.projectsveltos.io/v1alpha1
    kind: ClusterProfile
    name: kyverno
    uid: ae1812f8-f36d-4006-b8fc-da3c3deb380b
```

ClusterSummary.Spec.ClusterProfileSpec contains all the add-ons to be deployed

```yaml
  clusterProfileSpec:
    helmCharts:
    - chartName: kyverno/kyverno
      chartVersion: v3.0.1
      helmChartAction: Install
      releaseName: kyverno-latest
      releaseNamespace: kyverno
      repositoryName: kyverno
      repositoryURL: https://kyverno.github.io/kyverno/
      values: |
        admissionController:
          replicas: 1
```

ClusterSummary.Status.FeatureSummaries contains the status (whether add-ons are deployed or being deployed or any error occurred)

```yaml
status:
  dependencies: no dependencies
  featureSummaries:
  - featureID: Helm
    hash: VFvzbvlAg91J3Fp7q2hD1yHPwGaSuyD7JPEC6AuKT3E=
    lastAppliedTime: "2023-12-27T13:00:44Z"
    status: Provisioned
```

Also Sveltos has another CustomResourceDefinition, called ClusterConfiguration.

There is one ClusterConfiguration for each managed Cluster.
One or more ClusterProfile can match a managed cluster. All ClusterProfile instances matching a cluster, are listed as Owners for the ClusterConfiguration.

```yaml
apiVersion: config.projectsveltos.io/v1alpha1
kind: ClusterConfiguration
metadata:
  labels:
    projectsveltos.io/cluster-name: clusterapi-workload
    projectsveltos.io/cluster-type: Capi
  name: capi--clusterapi-workload
  namespace: default
  ownerReferences:
  - apiVersion: config.projectsveltos.io/v1alpha1
    kind: ClusterProfile
    name: kyverno
    uid: ae1812f8-f36d-4006-b8fc-da3c3deb380b
  - apiVersion: config.projectsveltos.io/v1alpha1
    kind: ClusterProfile
    name: nginx
    uid: 904412bd-92a8-4a66-bf98-581ad32dcb61
```

ClusterConfiguration.Status.ClusterProfileResources contains all resources deployed by Sveltos on that cluster (considering all matching ClusterProfile instances)

```yaml
status:
  clusterProfileResources:
  - Features:
    - charts:
      - appVersion: v1.10.0
        chartVersion: 3.0.1
        lastAppliedTime: "2023-12-27T13:00:16Z"
        namespace: kyverno
        releaseName: kyverno-latest
        repoURL: https://kyverno.github.io/kyverno/
      featureID: Helm
    profileName: kyverno
  - Features:
    - charts:
      - appVersion: 2.3.0
        chartVersion: 0.14.0
        lastAppliedTime: "2023-12-27T13:11:16Z"
        namespace: nginx
        releaseName: nginx-latest
        repoURL: https://helm.nginx.com/stable/
      featureID: Helm
    profileName: nginx
```
