### ISSUE TITLE
Support optional valuesFrom blocks in ClusterProfile/Profile templates

### ISSUE THREAD

**Issue by filippolmt** [projectsveltos/addon-controller#1185]
**Is your feature request related to a problem? Please describe.**
In my specific case, I’m using **Sveltos** to apply different configurations to clusters depending on their provider (`gcp` or `aws`) using `valuesFrom` blocks.
When a condition is not met (e.g., the cluster is neither GCP nor AWS), Sveltos still tries to load the resulting `ConfigMap`, which doesn’t exist, and this causes an error.

**Describe the solution you'd like**
To avoid these errors, it would be helpful to set `optional: true` in the conditional `valuesFrom` blocks. This way, Sveltos can safely skip non-existent `ConfigMaps` and continue processing.

Here’s a working example:

```yaml
valuesFrom:
  - kind: ConfigMap
    name: values-nginx-ingress-controller
    namespace: clusterprofile-nginx-ingress-controller
  - kind: ConfigMap
    name: "{{ if eq (index .Cluster.metadata.labels `provider`) `gcp` }}values-nginx-ingress-controller-gcp{{ elseif eq (index .Cluster.metadata.labels `provider`) `aws` }}values-nginx-ingress-controller-aws{{ end }}"
    namespace: clusterprofile-nginx-ingress-controller
    optional: true
  - kind: ConfigMap
    name: "{{ if eq (index .Cluster.metadata.labels `provider`) `gcp` }}values-nginx-ingress-controller-gcp-{{ .Cluster.metadata.name }}{{ end }}"
    optional: true
```
