### ISSUE TITLE
Unsupported and undocumented usage of Secrets for valuesFrom in helmCharts

### ISSUE THREAD

**Issue by sim500** [projectsveltos/addon-controller#1189]
# Problem Description

We're trying to deploy and Helm chart via a Profile, **importing the values from a Secret**.
As told here [Example: Update Helm Chart Values From Referenced ConfigMap/Secret
](https://projectsveltos.github.io/sveltos/addons/helm_charts/#example-update-helm-chart-values-from-referenced-configmapsecret) (although there isn't a specific example on how to use Secret in the documentation).

Here an example of what we're trying to deploy:

```
apiVersion: config.projectsveltos.io/v1beta1
kind: Profile
metadata:
  name: prometheus-stack
spec:
  clusterSelector:
    matchLabels:
      monitoring: persistent
  syncMode: ContinuousWithDriftDetection
  helmCharts:
  - repositoryURL: https://prometheus-community.github.io/helm-charts
    repositoryName: prometheus-community
    chartName: prometheus-community/kube-prometheus-stack
    chartVersion: 72.2.0
    releaseName: prometheus-stack
    releaseNamespace: prometheus-stack
    helmChartAction: Install
    valuesFrom:
      - kind: Secret
        name: grafana-admin-creds
        namespace: cluster-stage
```
And we have deployed the Secret of type **Opaque** as follows:
```
apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin-creds
  namespace: cluster-stage
data:
  grafana-admin-password.yaml: Z3JhZmFuYToKICBhZG1pblVzZXI6IGFkbWluCiAgYWRtaW5QYXNzd29yZDogYWRtaW4=
type: Opaque
```

# Logs

From the sveltos-dashboard:

```
failed to get secret cluster-stage/grafana-admin-creds: unsupported secret type
```

# System Information

SVELTOS VERSION: `0.53.0`
KUBERNETES VERSION: `1.30.5`
