### ISSUE TITLE
BUG: Sveltos tries to install the same release over and over again ignoring helm max history limit thrashing the child cluster api

### ISSUE THREAD

**Issue by wahabmk** [projectsveltos/addon-controller#1204]
# Problem Description

See https://github.com/k0rdent/kcm/issues/1498.

Sveltos Version: 0.52.2

**Comment by gianlucam76** [comment]
Thanks. I will verify sveltos passed the max release to helm. But have you tried setting this:

https://github.com/projectsveltos/addon-controller/blob/bc24298861108bae7945b53a07b6c7dde58c0dcd/api/v1beta1/spec.go#L797

Default behavior of sveltos is to keep retrying on failures unless the failure is marked as non retriable

**Comment by gianlucam76** [comment]
Please provide the Sveltos configuration used that kept failing.
 
I started with this and then did upgrade to 3.3.5, then 3.3.6, then 3.3.7, then 3.3.8 and finally 3.3.9 and Sveltos always set maxHistory to default (2) 

```yaml
apiVersion: config.projectsveltos.io/v1beta1
kind: ClusterProfile
metadata:
  name: deploy-kyverno
spec:
  dependsOn:
  - deploy-cert-manager
  clusterSelector:
    matchLabels:
      env: fv
  syncMode: Continuous
  helmCharts:
  - repositoryURL:    https://kyverno.github.io/kyverno/
    repositoryName:   kyverno
    chartName:        kyverno/kyverno
    chartVersion:     3.3.4
    releaseName:      kyverno-latest
    releaseNamespace: kyverno
    helmChartAction:  Install
```

```
helm history -n kyverno kyverno-latest
REVISION	UPDATED                 	STATUS    	CHART        	APP VERSION	DESCRIPTION     
5       	Fri May 16 05:05:09 2025	superseded	kyverno-3.3.8	v1.13.5    	Upgrade complete
6       	Fri May 16 05:08:17 2025	deployed  	kyverno-3.3.9	v1.13.6    	Upgrade complete
```
