### ISSUE TITLE
BUG: Drift detection for child cluster is looking for CR that are only defined in parent cluster

### ISSUE THREAD

**Issue by Banh-Canh** [projectsveltos/addon-controller#1205]
# Problem Description

```
apiVersion: lib.projectsveltos.io/v1beta1
kind: EventTrigger
metadata:
  name: minio-velero-cluster-eventtrigger
spec:
  sourceClusterSelector:
    matchLabels:
      type: mgmt
  eventSourceName: minio-velero-cluster-eventsource
  syncMode: ContinuousWithDriftDetection
  reloader: true
  oneForEvent: true
  policyRefs:
    - kind: ConfigMap
      name: minio-velero-bucket
      namespace: projectsveltos
```
i'm applying this with
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: minio-velero-bucket
  annotations:
    projectsveltos.io/instantiate: 'true'
data:
  zone.yaml: |
    apiVersion: minio.crossplane.io/v1
    kind: Bucket
    metadata:
      name: velero-{{ .Resource.metadata.name }}
    spec:
      deletionPolicy: Orphan
      forProvider: {}
      providerConfigRef:
        name: provider-config-clusters
```
It works as intended but the drift detection pod for the child cluster is spamming with logs saying:

```
E0517 08:37:06.476443       1 watcher.go:130] "Failed to get informer" err="no matches for kind \"Bucket\" in version \"minio.crossplane.io/v1\"" gvk="minio.crossplane.io/v1, Kind=Bucket"                                                  
I0517 08:37:06.476541       1 main.go:276] "failed to initialize manager no matches for kind \"Bucket\" in version \"minio.crossplane.io/v1\"" logger="setup" 
```
I have multiple cluster profile similar so it adds up

# System Information

_INSTRUCTIONS: Provide the system and application information below._

SVELTOS VERSION: ` v0.54.0 `
KUBERNETES VERSION: ` v1.31.4`

# Infos

The drift detection pod restart after some times, i believe it has to reach a certain point before crashing but I can't be sure.

Everything kinda works but I'm having some stability issues, and i'm unsure it's related.

Thank you !
