### ISSUE TITLE
BUG: Helm chart handover fails after removal from original managing profile

### ISSUE THREAD

**Issue by gianlucam76** [projectsveltos/addon-controller#1208]
# Problem Description

When two profiles (e.g., Profile A and Profile B) attempt to manage the same Helm chart, Sveltos correctly detects a conflict and prevents Profile B from taking over.

However, if the Helm chart is subsequently removed from Profile A, Profile B should be able to take over management of that chart. Currently, due to a bug, this handover does not occur. The system continues to block Profile B from managing the chart even though it is no longer managed by Profile A.

**Steps to Reproduce:**

Post this

```yaml
apiVersion: config.projectsveltos.io/v1beta1
kind: ClusterProfile
metadata:
  name: deploy-cert-manager
spec:
  clusterSelector:
    matchLabels:
      env: fv
  syncMode: ContinuousWithDriftDetection
  helmCharts:
  - repositoryURL:    https://kyverno.github.io/kyverno/
    repositoryName:   kyverno
    chartName:        kyverno/kyverno
    chartVersion:     3.3.4
    releaseName:      kyverno-latest
    releaseNamespace: kyverno
    helmChartAction:  Install
  - repositoryURL:    https://charts.jetstack.io
    repositoryName:   jetstack
    chartName:        jetstack/cert-manager
    chartVersion:     v1.16.3
    releaseName:      cert-manager
    releaseNamespace: cert-manager
    helmChartAction:  Install
    values: |
      crds:
        enabled: true
```

then post this 

```yaml
apiVersion: config.projectsveltos.io/v1beta1
kind: ClusterProfile
metadata:
  name: deploy-kyverno
spec:
  clusterSelector:
    matchLabels:
      env: fv
  syncMode: ContinuousWithDriftDetection
  helmCharts:
  - repositoryURL:    https://kyverno.github.io/kyverno/
    repositoryName:   kyverno
    chartName:        kyverno/kyverno
    chartVersion:     3.3.4
    releaseName:      kyverno-latest
    releaseNamespace: kyverno
    helmChartAction:  Install
```

At this point conflict is detected. So all good.

Then edit the first profile by removing kyverno so

```yaml
apiVersion: config.projectsveltos.io/v1beta1
kind: ClusterProfile
metadata:
  name: deploy-cert-manager
spec:
  clusterSelector:
    matchLabels:
      env: fv
  syncMode: ContinuousWithDriftDetection
  helmCharts:
  - repositoryURL:    https://charts.jetstack.io
    repositoryName:   jetstack
    chartName:        jetstack/cert-manager
    chartVersion:     v1.16.3
    releaseName:      cert-manager
    releaseNamespace: cert-manager
    helmChartAction:  Install
    values: |
      crds:
        enabled: true
```

Expectation is second profile will take over. Instead second profile remains in failed state and kyverno gets removed from managed cluster.

# System Information

_INSTRUCTIONS: Provide the system and application information below._

SVELTOS VERSION: v0.54.0
