### ISSUE TITLE
ClusterProfile installing multiple Helm charts does not update clusterconfigurations in case of failures

### ISSUE THREAD

**Issue by gianlucam76** [projectsveltos/addon-controller#305]
If a ClusterProfile is listing more than one Helm charts, and some are installed before an error happens, the installed Helm charts are not reported.

For instance, deploy following ClusterProfile 

```yaml
apiVersion: config.projectsveltos.io/v1alpha1
kind: ClusterProfile
metadata:
  name: multiple-helm-charts
spec:
  clusterSelector: env=fv
  syncMode: Continuous
  helmCharts:
  - repositoryURL:    https://prometheus-community.github.io/helm-charts
    repositoryName:   prometheus-community
    chartName:        prometheus-community/prometheus
    chartVersion:     23.4.0
    releaseName:      prometheus
    releaseNamespace: prometheus
    helmChartAction:  Install
  - repositoryURL:    https://grafana.github.io/helm-charts
    repositoryName:   bitnami
    chartName:        grafana/grafana
    chartVersion:     6.58.9
    releaseName:      grafana
    releaseNamespace: grafana
    helmChartAction:  Install
```

Prometheus gets installed. Grafana does not (as repositoryName is incorrectly set). Yet ClusterConfiguration does not list Prometheus as installed

```yaml
  apiVersion: config.projectsveltos.io/v1alpha1
  kind: ClusterConfiguration
  metadata:
    creationTimestamp: "2023-08-20T14:27:28Z"
    generation: 1
    labels:
      projectsveltos.io/cluster-name: clusterapi-workload
      projectsveltos.io/cluster-type: Capi
    name: capi--clusterapi-workload
    namespace: default
    ownerReferences:
    - apiVersion: config.projectsveltos.io/v1alpha1
      kind: ClusterProfile
      name: multiple-helm-charts
      uid: 634678b8-ff6f-479c-acae-de5dd50ab0c2
    resourceVersion: "20595"
    uid: 8b2db1ac-cfdc-418b-a5ec-e20fce064179
  status:
    clusterProfileResources:
    - clusterProfileName: multiple-helm-charts
```

same is visible with 

```
kubectl exec -it -n projectsveltos sveltosctl-0 -- ./sveltosctl show addons 
+---------+---------------+-----------+------+---------+------+------------------+
| CLUSTER | RESOURCE TYPE | NAMESPACE | NAME | VERSION | TIME | CLUSTER PROFILES |
+---------+---------------+-----------+------+---------+------+------------------+
+---------+---------------+-----------+------+---------+------+------------------+
```

**Comment by gianlucam76** [comment]
Correct ClusterProfile is

```yaml
apiVersion: config.projectsveltos.io/v1alpha1
kind: ClusterProfile
metadata:
  name: multiple-helm-charts
spec:
  clusterSelector: env=fv
  syncMode: Continuous
  helmCharts:
  - repositoryURL:    https://prometheus-community.github.io/helm-charts
    repositoryName:   prometheus-community
    chartName:        prometheus-community/prometheus
    chartVersion:     23.4.0
    releaseName:      prometheus
    releaseNamespace: prometheus
    helmChartAction:  Install
  - repositoryURL:    https://grafana.github.io/helm-charts
    repositoryName:   grafana
    chartName:        grafana/grafana
    chartVersion:     6.58.9
    releaseName:      grafana
    releaseNamespace: grafana
    helmChartAction:  Install
```
