### ISSUE TITLE
Helm chart with CustomResourceDefinition and instances of such CRDs

### ISSUE THREAD

**Issue by gianlucam76** [projectsveltos/addon-controller#308]
If an Helm chart contains both CustomResourceDefinitions and instances of such CRDs, deploying such helm chart with Sveltos will fail.

For instance

``` yaml
apiVersion: config.projectsveltos.io/v1alpha1
kind: ClusterProfile
metadata:
  name: kubevela-core
spec:
  clusterSelector: env=fv
  syncMode: Continuous
  helmCharts:
  - repositoryURL:    https://kubevela.github.io/charts
    repositoryName:   kubevela
    chartName:        kubevela/vela-core
    chartVersion:     1.9.6
    releaseName:      kubevela-core-latest
    releaseNamespace: vela-system
    helmChartAction:  Install
```

The reason is Sveltos uses Helm in dry run mode first to get list of resources Helm charts would deploy. It then validates those resources against compliance policies (both OpenAPI and Lua ones).

But dry run for helm would fail for an helm chart with both CRDs and instances of such CRDs. 

While this behaviour needs to be called out in documentation, if no compliance policies are defined, Sveltos must be able to deploy such Helm charts.
