### ISSUE TITLE
BUG: configuration drift detection does not work in the scenario described by this bug

### ISSUE THREAD

**Issue by gianlucam76** [projectsveltos/addon-controller#363]
# Problem Description

When deploying this ClusterPolicy, configuration drift detection does not work.

```yaml
apiVersion: config.projectsveltos.io/v1alpha1
kind: ClusterProfile
metadata:
  name: podinfo
spec:
  clusterSelector: env=fv
  helmCharts:
  - chartName: podinfo/podinfo
    chartVersion: v6.5.1
    helmChartAction: Install
    releaseName: podinfo
    releaseNamespace: test
    repositoryName: podinfo
    repositoryURL: https://stefanprodan.github.io/podinfo
  syncMode: ContinuousWithDriftDetection
```

An initial debug of the issue indicates the problem to be in addon-controller.

Addon-controller, when a ClusterProfile syncMode is set to ContinuousWithDriftDetection, gets list of resources deployed and pass it to drift-detection-manager.

In this case,  the manifest returned by Helm  does not have namespace even for namespace resources..

```yaml
    - group: apps
      kind: Deployment
      name: podinfo
      version: v1
```

while in general in other cases this is what is returned

```yaml
    - group: apps
      kind: Deployment
      name: kyverno-admission-controller
      namespace: kyverno
      version: v1
```

The missing namespace information is causing drift-detection-manager to fail.
