### ISSUE TITLE
BUG: addon-controller keeps redeploying cilium

### ISSUE THREAD

**Issue by gianlucam76** [projectsveltos/addon-controller#419]
# Problem Description

Posting this Profile (ClusterProfile is same)

```yaml
  apiVersion: config.projectsveltos.io/v1alpha1
  kind: Profile
  metadata:
    name: cilium
  spec:
    clusterSelector: cni=cilium
    helmCharts:
    - chartName: cilium/cilium
      chartVersion: v1.14.5
      helmChartAction: Install
      releaseName: cilium
      releaseNamespace: kube-system
      repositoryName: cilium
      repositoryURL: https://helm.cilium.io/
      values: |
        null
    reloader: false
    stopMatchingBehavior: WithdrawPolicies
    syncMode: ContinuousWithDriftDetection
```

depending on how long Sveltos takes to install cilium first time, addon-controller, due to drift-detection, goes in a loop.

Drift-detection starts detecting this

```
I0108 18:08:57.316119       1 watcher.go:93] "Resource in ResourceSummary civo2--p--cilium-sveltos-civo-cluster-2 potentially drifted (Secret kube-system/hubble-server-certs)" gvk="/v1, Kind=Secret" key="kube-system/hubble-server-certs"
```

and addon-controller then keeps redeploying cilium.

This seems to be an issue with  either addon-controller or drift-detection manager.
Either addon-controller redeploys helm chart first time even though that is not needed or drift-detection incorrectly detects first possible drift.

Cilium documentation: "When using Helm, TLS certificates are (re-)generated every time Helm is used for install or upgrade"
