### ISSUE TITLE
Deploying large CRDs with Spec.PolicyRefs

### ISSUE THREAD

**Issue by rbjorklin** [projectsveltos/addon-controller#428]
**Is your feature request related to a problem? Please describe.**
I like the idea of templating/rendering my helm charts before applying them as this allows me to review them in Github's diff view. I have currently been doing this by having the output of helm template go into a Configmap as is described in the section on [Spec.PolicyRefs](https://projectsveltos.github.io/sveltos/addons/clusterprofile/#specpolicyrefs). Unfortunately this fails for [Kyverno](https://github.com/kyverno/kyverno/) as one of the CRDs is bigger than 1MB. The [Kubernetes documentation](https://kubernetes.io/docs/concepts/configuration/configmap/#motivation) has this to say:

> **Note:** A ConfigMap is not designed to hold large chunks of data. The data stored in a ConfigMap cannot exceed 1 MiB. If you need to store settings that are larger than this limit, you may want to consider mounting a volume or use a separate database or file service.

**Describe the solution you'd like**
If supporting this workflow is out of scope for Project Sveltos I would still encourage adding a note to the documentation around PolicyRefs stating that the max size of a Confimap is 1MB and this will limit its usefulness.

**Describe alternatives you've considered**
This can be worked around by blindly having Project Sveltos render and apply charts.

**Additional context**
Not at the moment.

**Comment by gianlucam76** [comment]
Thank you @rbjorklin for raising this issue. I will definitely add a note to the documentation.  I would also love to discuss with you a possible solution. if you have any idea/suggestion would love to hear it.

What if though Sveltos allows getting the YAML from a GitRepository/Bucket?

So something like allowing PolicyRefs to also point to a Flux resource and get the YAML from there

  - namespace: <NAMESPACE of resource>
    name: <Name of the resource>
    kind: GitRepository/Bucket
    path: <path where YAML is>

In this case there will be no limit. Downside is that now Flux needs to be present in the management cluster as well. 
But Flux will be used to send configuration to management cluster, Sveltos to deploy it to the managed cluster.

**Comment by gianlucam76** [comment]
@rbjorklin thanks again for filing this issue. 

I have:
1. updated documentation
2. added supports to get YAML from git repository (or bucket) in this [PR](https://github.com/projectsveltos/addon-controller/pull/449)

For instance I created this git [repository](https://github.com/gianlucam76/yaml_flux/tree/main/kyverno) that contains the output of helm template kyverno kyverno/kyverno 

Then I had Flux sync the content of this repository in the management cluster:

```yaml
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  creationTimestamp: "2024-02-07T13:53:12Z"
  finalizers:
  - finalizers.fluxcd.io
  generation: 1
  labels:
    kustomize.toolkit.fluxcd.io/name: flux-system
    kustomize.toolkit.fluxcd.io/namespace: flux-system
  name: flux-system
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  secretRef:
    name: flux-system
  timeout: 60s
  url: https://github.com/gianlucam76/yaml_flux.git
``` 

Finally I created a ClusterProfile that references the GitRepository and takes and deploys content in the __kyverno__ directory

```yaml
apiVersion: config.projectsveltos.io/v1alpha1
kind: ClusterProfile
metadata:
  name: deploy-kyverno-resources
spec:
  clusterSelector: env=fv
  policyRefs:
  - kind: GitRepository
    name: flux-system
    namespace: flux-system
    path: kyverno
```
