### ISSUE TITLE
Allow base64 encoding/decoding in templates

### ISSUE THREAD

**Issue by thecodeassassin** [projectsveltos/addon-controller#518]
**Is your feature request related to a problem? Please describe.**

Some charts don't allow you to provide a secret name to reference actual secrets (such as NATS)

```yaml
 config:
        merge:
          no_auth_user: public
          accounts:
            public:
              users:
              - {user: public, permissions: {subscribe: ["user.notifications.*", "public.>"], publish: ["public.>"]}}
            private:
              jetstream: enabled
              users:
              - {user: admin, password: "{{ (index .MgmtResources "NatsSecret").data.token }}", permissions: {subscribe: [">"], publish: [">"]}}
```              
              
so one can use secret refs to reference the secret in the template. But these values are base64 encoded. Right now this is not an issue since NATS supports bcrypt values that are safe to be put in a configmap as they aren't plaintext.

But it would be great if secrets could be templated like this by allowing base64 encoding and decoding.

1 worker.go:238] "added to result with err template: mgmt-mgmt-nats/nats:11: function \"base64\" not defined" logger="deployer" worker="9" key="mgmt:::mgmt:::Sveltos:::nats-sveltos-mgmt:::Helm:::false"

**Describe the solution you'd like**
Allow base64 encoding and decoding of values in templates
