### ISSUE TITLE
Cluster-Selector: The Kubernetes native way

### ISSUE THREAD

**Issue by oliverbaehler** [projectsveltos/addon-controller#587]
**Is your feature request related to a problem? Please describe.**

Currently the selector for `ClusterProfiles` and `Profile` is kinda primitive. Not to say it would not be sufficient. However: what if we used a selector declaration which is a bit more native to Kubernetes aka the LabelSelector struct:

```
...
   selector:
       matchLabels:
          environment: production
       matchExpressions:
          - { key: tier, operator: In, values: [cache] }
```

This would  **not** replace the current option, for compatibility reasons. The would probably be combined.

**Describe the solution you'd like**
Implement the proposed selector, if it's accepted as feature.
