### ISSUE TITLE
feat: arbritrary data for non CAPI-Clusters

### ISSUE THREAD

**Issue by oliverbaehler** [projectsveltos/addon-controller#588]
**Is your feature request related to a problem? Please describe.**
As mentioned here: https://github.com/projectsveltos/addon-controller/issues/447

How do you solve the case, where you have a new cluster registered, let's say this eg.
```
apiVersion: v1
items:
- apiVersion: lib.projectsveltos.io/v1alpha1
  kind: SveltosCluster
  metadata:
    creationTimestamp: "2024-06-12T09:13:55Z"
    generation: 1
    labels:
      capsule.clastix.io/tenant: xmodels
      env: production
      is-credential-preset: "true"
      overwrite: this
      project-id: xmodels
    name: pdl6npm7qp
    namespace: cluster-pdl6npm7qp
    spec: {}
   ```
Now I have seen here (https://projectsveltos.github.io/sveltos/template/template/ - Variables) that you have access to a lot of CAPI attributes. In our case we don't have access but I still need to configure my charts with certain cluster properties.

So there needs to be a way to add more data to sveltosclusters, which are non CAPI provided. A simple approach, adding a extra context field to sveltosclusters, where I can pass my additional information (essentially an interface of values):

```
apiVersion: lib.projectsveltos.io/v1alpha1
kind: SveltosCluster
metadata:
  creationTimestamp: "2024-06-12T09:13:55Z"
  generation: 1
  labels:
    capsule.clastix.io/tenant: xmodels
    env: production
    is-credential-preset: "true"
    overwrite: this
    project-id: xmodels
  name: pdl6npm7qp
  namespace: cluster-pdl6npm7qp
  uid: 02f9f1d7-b93a-4944-a449-d77c3bb3672d
spec:
  context:
    address:
      ip: 10.123.11.5
      port: 6443
      url: https://pdl6npm7qp.some.cloud:6443
    versions:
      apiserver: 1.28.9
      controlPlane: 1.28.9
      controllerManager: 1.28.9
      oldestNodeVersion: 1.28.9
      scheduler: 1.28.9
```

**Describe the solution you'd like**
We would like to be able to add data to registered clusters, which are not CAPI native. Add an additional API field for Sveltoscluster, to add Arbitrary data. no further changes should be necessary, since the rest can be handled with sprig templating.

**Describe alternatives you've considered**
We are aware, that this could be done via the clusters metadata, however we would like to provide a bit more complex arbritray data.

**Additional context**
