### ISSUE TITLE
BUG: [pre deployment patches with multiple resources

### ISSUE THREAD

**Issue by gianlucam76** [projectsveltos/addon-controller#625]
# Problem Description

```bash
wget https://github.com/fluxcd/flux2/releases/download/v2.3.0/install.yaml
kubectl create configmap install-flux --from-file=install.yaml
```

Then create a ClusterProfile referencing above ConfigMap with patches

```yaml
apiVersion: config.projectsveltos.io/v1beta1
kind: ClusterProfile
metadata:
  name: fluxcd
spec:
  clusterSelector:
    matchLabels:
      env: fv
  syncMode: ContinuousWithDriftDetection
  policyRefs:
  - name: install-flux
    namespace: default
    kind: ConfigMap
  patches:
  - target:
      kind: Namespace
      name: ".*"
    patch: |
      - op: add
        path: /metadata/labels/type
        value: operator
```

Resources are not deployed
