### ISSUE TITLE
BUG: deploymentType: Local does not work with Profile

### ISSUE THREAD

**Issue by lukasmrtvy** [projectsveltos/addon-controller#828]
# Problem Description

`deploymentType: Local` does not work well with `Profile`, resources are not created, although ClusterSummary says the oposite..

Examples:
```
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test
  annotations:
    projectsveltos.io/template: "true"
data:
  autoscaler.yaml: |
    apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: "{{ .Cluster.metadata.name }}-test"
      namespace: "{{ .Cluster.metadata.namespace }}"
  random.yaml: |
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: "{{ .Cluster.metadata.name }}-test"
      namespace: "{{ .Cluster.metadata.namespace }}"
```

```
---
apiVersion: config.projectsveltos.io/v1alpha1
kind: Profile
metadata:
  name: ${CLUSTER_NAME}-test
spec:
  stopMatchingBehavior: WithdrawPolicies
  clusterSelector: name=${CLUSTER_NAME}
  syncMode: ContinuousWithDriftDetection
  policyRefs:
  - deploymentType: Local
    kind: ConfigMap
    name: test
```

# System Information

CLUSTERAPI VERSION: `v1.8.4`
SVELTOS VERSION: `v0.42.0`
KUBERNETES VERSION: `v1.30.5+k3s1`

# Logs

``
kubectl logs addon-controller-587cb6-6vv5l -n projectsveltos |grep "deploying resource"

E1117 12:37:20.873127       1 clustersummary_controller.go:381] "failed to deploy" err="deploying resources failed: request is queued" controller="clustersummary" controllerGroup="config.projectsveltos.io" controllerKind="ClusterSummary" ClusterSummary="example/p--mycluster-test-capi-mycluster" namespace="example" name="p--mycluster-test-capi-mycluster" reconcileID="4d98851c-313a-4316-860a-7e5fd7c3f02d"
E1117 12:37:20.910960       1 clustersummary_controller.go:381] "failed to deploy" err="deploying resources failed: request is queued" controller="clustersummary" controllerGroup="config.projectsveltos.io" controllerKind="ClusterSummary" ClusterSummary="example/p--mycluster-test-capi-mycluster" namespace="example" name="p--mycluster-test-capi-mycluster" reconcileID="8cf4ee62-95d8-4f28-94ef-01fa65309aaf"
E1117 12:37:20.934928       1 clustersummary_controller.go:381] "failed to deploy" err="deploying resources failed: feature is still being provisioned" controller="clustersummary" controllerGroup="config.projectsveltos.io" controllerKind="ClusterSummary" ClusterSummary="example/p--mycluster-test-capi-mycluster" namespace="example" name="p--mycluster-test-capi-mycluster" reconcileID="f26cc1f6-2f49-4711-a874-2ac0cff38a88"
I1117 12:37:21.133381       1 handlers_utils.go:403] "deploying resource ServiceAccount example/mycluster-test (deploy to management cluster: true)" logger="deployer" worker="9" key="example:::mycluster:::Capi:::p--mycluster-test-capi-mycluster:::Resources:::false" cluster="example/mycluster" clusterSummary="p--mycluster-test-capi-mycluster" admin="/" configMapNamespace="example" configMapName="test"
E1117 12:37:21.288807       1 clustersummary_controller.go:381] "failed to deploy" err="deploying resources failed: feature is still being provisioned" controller="clustersummary" controllerGroup="config.projectsveltos.io" controllerKind="ClusterSummary" ClusterSummary="example/p--mycluster-test-capi-mycluster" namespace="example" name="p--mycluster-test-capi-mycluster" reconcileID="5d84f753-ebb1-4185-9e60-9c990275c4c9"
E1117 12:37:21.307607       1 clustersummary_controller.go:381] "failed to deploy" err="deploying resources failed: feature is still being provisioned" controller="clustersummary" controllerGroup="config.projectsveltos.io" controllerKind="ClusterSummary" ClusterSummary="example/p--mycluster-test-capi-mycluster" namespace="example" name="p--mycluster-test-capi-mycluster" reconcileID="a025fe65-7996-4238-8378-ae4d71d7acaf"
E1117 12:48:37.211471       1 clustersummary_controller.go:381] "failed to deploy" err="deploying resources failed: request is queued" controller="clustersummary" controllerGroup="config.projectsveltos.io" controllerKind="ClusterSummary" ClusterSummary="example/p--mycluster-test-capi-mycluster" namespace="example" name="p--mycluster-test-capi-mycluster" reconcileID="6d184cb1-b3cb-413f-91cc-93b4cec4df1a"
E1117 12:48:37.226197       1 clustersummary_controller.go:381] "failed to deploy" err="deploying resources failed: feature is still being provisioned" controller="clustersummary" controllerGroup="config.projectsveltos.io" controllerKind="ClusterSummary" ClusterSummary="example/p--mycluster-test-capi-mycluster" namespace="example" name="p--mycluster-test-capi-mycluster" reconcileID="5fa31017-e74f-4bd3-8b01-acda2ab46886"
I1117 12:48:39.848349       1 handlers_utils.go:403] "deploying resource ConfigMap example/mycluster-test (deploy to management cluster: true)" logger="deployer" worker="8" key="example:::mycluster:::Capi:::p--mycluster-test-capi-mycluster:::Resources:::false" cluster="example/mycluster" clusterSummary="p--mycluster-test-capi-mycluster" admin="/" configMapNamespace="example" configMapName="test"
I1117 12:48:39.914576       1 handlers_utils.go:403] "deploying resource ServiceAccount example/mycluster-test (deploy to management cluster: true)" logger="deployer" worker="8" key="example:::mycluster:::Capi:::p--mycluster-test-capi-mycluster:::Resources:::false" cluster="example/mycluster" clusterSummary="p--mycluster-test-capi-mycluster" admin="/" configMapNamespace="example" configMapName="test"
E1117 12:48:39.971915       1 clustersummary_controller.go:381] "failed to deploy" err="deploying resources failed: feature is still being provisioned" controller="clustersummary" controllerGroup="config.projectsveltos.io" controllerKind="ClusterSummary" ClusterSummary="example/p--mycluster-test-capi-mycluster" namespace="example" name="p--mycluster-test-capi-mycluster" reconcileID="660183fb-5960-4f1a-abba-3fba7cfbf18c"
E1117 12:48:39.987980       1 clustersummary_controller.go:381] "failed to deploy" err="deploying resources failed: feature is still being provisioned" controller="clustersummary" controllerGroup="config.projectsveltos.io" controllerKind="ClusterSummary" ClusterSummary="example/p--mycluster-test-capi-mycluster" namespace="example" name="p--mycluster-test-capi-mycluster" reconcileID="1217447c-b944-489d-aada-fbc890b1134b"
``
