### ISSUE TITLE
Template: add a method to copy a resource

### ISSUE THREAD

**Issue by gianlucam76** [projectsveltos/addon-controller#847]
**Is your feature request related to a problem? Please describe.**
It is common to use Sveltos to fetch resources in the management cluster and copy those to matching managed clusters.

Today code in the template section is kind of too long. For instance

```yaml
apiVersion: config.projectsveltos.io/v1beta1
kind: ClusterProfile
metadata:
  name: sync-secrets
spec:
  clusterSelector:
    matchLabels:
      env: staging      
  templateResourceRefs:
  - resource:
     apiVersion: v1
     kind: Secret
     name: eso-vault-secret-sync
     namespace: default
    identifier: ExternalSecret
  policyRefs:
    - kind: ConfigMap
      name: info
      namespace: default
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: info
  namespace: default
  annotations:
    projectsveltos.io/template: "true"  # add annotation to indicate Sveltos content is a template
data:
  secret.yaml: |-
    apiVersion: v1
    kind: Secret
    metadata:
      name: default
      namespace: {{ (getResource "ExternalSecret").metadata.namespace }}
    data:
      content: {{ (getResource "ExternalSecret").data.username }}
```

It would be nice to replace the section 

```yaml
  secret.yaml: |-
    apiVersion: v1
    kind: Secret
    metadata:
      name: default
      namespace: {{ (getResource "ExternalSecret").metadata.namespace }}
    data:
      content: {{ (getResource "ExternalSecret").data.username }}
```

with something like 

```yaml
  secret.yaml: |-
    {{ (clone "ExternalSecret") }}
```
