### ISSUE TITLE
BUG: DryRun mode and winning tier

### ISSUE THREAD

**Issue by gianlucam76** [projectsveltos/addon-controller#894]
# Problem Description

I have a ClusterProfile deploying an HelmChart. 

```yaml
apiVersion: config.projectsveltos.io/v1beta1
kind: ClusterProfile
metadata:
  name: deploy-kyverno-gke
spec:
  tier: 10
  clusterSelector:
    matchLabels:
      type: gke
  syncMode: Continuous
  helmCharts:
  - repositoryURL:    https://kyverno.github.io/kyverno/
    repositoryName:   kyverno
    chartName:        kyverno/kyverno
    chartVersion:     v3.2.5
    releaseName:      kyverno-latest
    releaseNamespace: kyverno
    helmChartAction:  Install
```

Now I create a new ClusterProfile, in DryRun mode, with a better tier. 

```yaml
apiVersion: config.projectsveltos.io/v1beta1
kind: ClusterProfile
metadata:
  name: deploy-kyverno
spec:
  clusterSelector:
    matchLabels:
      env: production
  continueOnConflict: false
  helmCharts:
  - chartName: kyverno/kyverno
    chartVersion: v3.2.6
    helmChartAction: Install
    releaseName: kyverno-latest
    releaseNamespace: kyverno
    repositoryName: kyverno
    repositoryURL: https://kyverno.github.io/kyverno/
    values: |
      admissionController:
        replicas: 3
      backgroundController:
        replicas: 3
      reportsController:
        replicas: 3
      cleanerController:
        replicas: 3
  reloader: false
  stopMatchingBehavior: WithdrawPolicies
  syncMode: DryRun
  tier: 5
```

This second profile should win the conflict and message should be Kyverno would be upgraded. Instead  the show dryrun message is reports incorrectly a conflict

```
| gke/cluster  | helm release             | kyverno   | kyverno-latest              | Conflict      | Cannot manage it. Currently    | ClusterProfile/deploy-kyverno           |
|              |                          |           |                             |               | managed by ClusterProfile      |                                         |
|              |                          |           |                             |               | deploy-kyverno-gke             |    
```

``
[insert problem description here]
``

# System Information

_INSTRUCTIONS: Provide the system and application information below._

CLUSTERAPI VERSION: ` [e.g. v1.2.4 etc.] `
SVELTOS VERSION: ` [e.g. PRODUCT version X.Y.Z] `
KUBERNETES VERSION: ` [e.g. v1.25 etc.] `

# Logs

_INSTRUCTIONS: Provide any additional information you think would be helpful below.  Large files, logs, etc. can be attached to this issue so long as they meet the GitHub attachment guidelines described here: https://help.github.com/en/github/managing-your-work-on-github/file-attachments-on-issues-and-pull-requests_

``
[insert additional information here]
``
