### ISSUE TITLE
BUG: TLS error in addon-controller logs

### ISSUE THREAD

**Issue by filippolmt** [projectsveltos/addon-controller#972]
**Description:**

# Problem Description

After applying the following manifest, which creates a ClusterProfile:

```yaml
apiVersion: config.projectsveltos.io/v1beta1
kind: ClusterProfile
metadata:
  name: base-configuration
spec:
  clusterSelector:
    matchLabels:
      applications: base
  continueOnConflict: false
  helmCharts:
    - chartName: cert-manager
      chartVersion: v1.12.4
      helmChartAction: Install
      registryCredentialsConfig:
        ca:
          name: ca-certificate
          namespace: projectsveltos
        credentials:
          name: docker-login-https-nexus-example-repository
          namespace: projectsveltos
        insecureSkipTLSVerify: false
      releaseName: cert-manager
      releaseNamespace: cert-manager
      repositoryName: cert-manager
      repositoryURL: https://nexus.example.com/repository/
      values: |
        resources:
          requests:
            memory: "128Mi"
            cpu: "10m"
          limits:
            memory: "128Mi"
            cpu: "100m"
```

I encounter the following error in the **addon-controller** logs:

```
level=info msg="Error logging in to endpoint, trying next endpoint" error="Get \"https://example.com/v2/\": tls: failed to verify certificate: x509: certificate signed by unknown authority"
```

This issue occurs both when I add the certificate to the ClusterProfile configuration and when I try to skip certificate verification.

Additionally, the Helm registry being used is **not OCI-compliant**.

---

**System Information**

- **CLUSTERAPI VERSION:** `v1.29.4`  
- **SVELTOS VERSION:** `v0.45.0`  
- **KUBERNETES VERSION:** `v1.29.4`  

---

**Logs**

No additional logs are available at the moment.
