### ISSUE TITLE
Feature Request: Enhance ClusterSet/Set with Custom Failover Support

### ISSUE THREAD

**Issue by kahirokunn** [projectsveltos/addon-controller#981]
I'll help format this as a feature request.

Title: Enhance ClusterSet/Set with KeptnMetric-based Failover Support

**Is your feature request related to a problem? Please describe.**
Currently, while ClusterSet/Set provides failover functionality, it could be enhanced by leveraging existing CNCF capabilities for metrics-based failover decisions. There's an opportunity to integrate with established tools rather than implementing custom solutions.

**Describe the solution you'd like**
I propose enhancing ClusterSet/Set to support failover triggers based on KeptnMetric custom resources. The Keptn Lifecycle Toolkit already provides a metrics operator (https://github.com/keptn/lifecycle-toolkit/tree/main/metrics-operator) that we can leverage.

This integration would allow ClusterSet to make failover decisions based on various metrics like HTTP success rates, kubelet error rates, and kube-apiserver error rates. Here's a proof of concept example:

```yaml
apiVersion: lib.projectsveltos.io/v1beta1
kind: ClusterSet
metadata:
  name: prod
spec:
  clusterSelector:
    matchLabels:
      env: prod
  maxReplicas: 1
  templateResourceRefs:
    - resource:
        apiVersion: metrics.keptn.sh/v1
        kind: KeptnMetric
        name: "{{ .Cluster.metadata.name }}-http-success-rate-metric"
        namespace: "{{ .Cluster.metadata.namespace }}"
      identifier: httpSuccessRate
    - resource:
        apiVersion: metrics.keptn.sh/v1
        kind: KeptnMetric
        name: "{{ .Cluster.metadata.name }}-kubelet-error-rate-metric"
        namespace: "{{ .Cluster.metadata.namespace }}"
      identifier: kubeletErrorRate
    - resource:
        apiVersion: metrics.keptn.sh/v1
        kind: KeptnMetric
        name: "{{ .Cluster.metadata.name }}-kubeApiserver-error-rate-metric"
        namespace: "{{ .Cluster.metadata.namespace }}"
      identifier: kubeApiserverErrorRate
  validateHealths:
    - script: |
        function evaluate()
          local hs = {
              healthy = true,
              message = "cluster is healthy"
          }

          local httpSuccessRate       = tonumber(ctx.httpSuccessRate.status.value) or 0
          local kubeletErrorRate      = tonumber(ctx.kubeletErrorRate.status.value) or 0
          local kubeApiserverErrorRate = tonumber(ctx.kubeApiserverErrorRate.status.value) or 0

          if httpSuccessRate <= 0.1 and (kubeletErrorRate + kubeApiserverErrorRate) <= 1.0 then
              hs.healthy = false
              hs.message = "too many errors"
          end

          return hs
        end
```

**Describe alternatives you've considered**
The main alternative would be implementing custom metrics collection and evaluation within ClusterSet/Set itself. However, this would:
1. Increase implementation complexity and maintenance burden
2. Duplicate functionality that already exists in the CNCF ecosystem
3. Require additional testing and validation of metrics collection

**Additional context**
This approach offers several benefits:
1. Leverages existing CNCF capabilities rather than reinventing the wheel
2. Reduces implementation costs by utilizing established metrics collection
3. Provides a flexible framework for defining various metrics-based failover scenarios
4. Integrates smoothly with existing Kubernetes custom resources

**Comment by kahirokunn** [comment]
I was thinking of revising the proposal as follows.

# Introduction of Independent Custom Resources for Health Checks and Metrics-based Failover

## Is this feature request related to a problem? Please explain in detail.
Currently, ClusterSet/Set has become quite feature-rich by allowing the definition of "what states are considered unhealthy" within its own spec. Specifically, it includes sections such as variableResourceRefs and validateHealths, which enable metrics-based failover (for example, utilizing KeptnMetric). However, cramming all this logic into the ClusterSet/Set resource increases complexity and risks making future feature extensions more difficult. Furthermore, the lifecycles of different aspects - cluster management and health check logic - often belong to different roles, suggesting a design principle that these concerns should be separated.

## What solution would you like?
Instead of adding variableResourceRefs and validateHealths directly to ClusterSet/Set, introduce a new custom resource (e.g., "ClusterHealthPolicy" or "FailoverPolicy") for defining health check jobs, metric references, and validation logic in a clearly separated manner. ClusterSet/Set can reference (or be referenced by) these new custom resources via labels, selectors, or explicit references.

For example, the new CR would look like this:

```yaml
apiVersion: lib.projectsveltos.io/v1beta1
kind: ClusterHealthPolicy
metadata:
  name: prod
spec:
  # Link with clusters via selectors, similar to ClusterSet/Set
  clusterSelector:
    matchLabels:
      env: prod

  variableResourceRefs:
    - resource:
        apiVersion: metrics.keptn.sh/v1
        kind: KeptnMetric
        name: "{{ .Cluster.metadata.name }}-http-success-rate-metric"
        namespace: "{{ .Cluster.metadata.namespace }}"
      identifier: httpSuccessRate
    - resource:
        apiVersion: metrics.keptn.sh/v1
        kind: KeptnMetric
        name: "{{ .Cluster.metadata.name }}-kubelet-error-rate-metric"
        namespace: "{{ .Cluster.metadata.namespace }}"
      identifier: kubeletErrorRate
    - resource:
        apiVersion: metrics.keptn.sh/v1
        kind: KeptnMetric
        name: "{{ .Cluster.metadata.name }}-kubeApiserver-error-rate-metric"
        namespace: "{{ .Cluster.metadata.namespace }}"
      identifier: kubeApiserverErrorRate

  validateHealths:
    - # Pod-based checks to verify cluster health
      pod:
        intervalSeconds: 60
        successRateSeconds: 300
        successRateThresholdPercent: 10.5
        consecutiveFailureThreshold: 3
        template:
          metadata:
            labels:
              network-policy: "allow-all"
          spec:
            restartPolicy: Never
            volumes:
              - name: data-volume
                persistentVolumeClaim:
                  claimName: ceph
            containers:
              - name: check-pvc-mount
                image: busybox
                command:
                - /bin/sh
                - -c
                - |
                  echo "Checking PVC mount..."
                  ls -la /mnt/pvc
                  if [ $? -ne 0 ]; then
                    echo "PVC mount check failed"
                    exit 1
                  fi
                volumeMounts:
                  - name: pvc-volume
                    mountPath: /mnt/pvc

              - name: internal-check
                image: curlimages/curl:latest
                command:
                - /bin/sh
                - -c
                - |
                  echo "Checking internal service..."
                  if [ "$(curl -s -o /dev/null -w '%{http_code}' http://internal-service:80/healthz)" != "200" ]; then
                    echo "Health check failed (non-200 status)"
                    exit 1
                  fi
                  nc -zv grpc-service 50051

              - name: aws-check
                image: amazon/aws-cli
                env:
                  - name: AWS_ACCESS_KEY_ID
                    valueFrom:
                      secretKeyRef:
                        name: aws-credentials
                        key: AWS_ACCESS_KEY_ID
                  - name: AWS_SECRET_ACCESS_KEY
                    valueFrom:
                      secretKeyRef:
                        name: aws-credentials
                        key: AWS_SECRET_ACCESS_KEY
                command:
                - /bin/sh
                - -c
                - |
                  echo "Checking AWS API..."
                  aws apigateway get-rest-apis --query 'items[0].name' --output text

              - name: external-check
                image: curlimages/curl
                command:
                - /bin/sh
                - -c
                - |
                  echo "Checking external service..."
                  if [ "$(curl -s -o /dev/null -w '%{http_code}' https://example.com)" != "200" ]; then
                    echo "External service check failed (non-200 status)"
                    exit 1
                  fi

              - name: internet-check
                image: busybox
                command:
                - /bin/sh
                - -c
                - |
                  echo "Checking internet connectivity..."
                  ping -c 3 8.8.8.8 || echo "Internet connection failed"

    - language: lua
      duration: 10m
      script: |
        function evaluate()
          local hs = {
            healthy = true,
            message = "Cluster is healthy"
          }

          local httpSuccessRate        = tonumber(ctx.httpSuccessRate.status.value) or 0
          local kubeletErrorRate       = tonumber(ctx.kubeletErrorRate.status.value) or 0
          local kubeApiserverErrorRate = tonumber(ctx.kubeApiserverErrorRate.status.value) or 0

          if httpSuccessRate <= 0.1 and (kubeletErrorRate + kubeApiserverErrorRate) <= 1.0 then
              hs.healthy = false
              hs.message = "Too many errors"
          end

          return hs
        end
```

Existing ClusterSet/Set would simply reference (or be discovered by) this new custom resource to handle metrics-based failover logic, keeping core cluster grouping and scheduling logic in one place while delegating health checks and variable references to a resource explicitly designed for that purpose.

## Considered Alternatives
1. Continuing to embed metrics and health check logic directly in ClusterSet/Set would result in an increasingly large and complex spec, making future maintenance and feature enhancements difficult.
2. Implementing custom metrics collection within ClusterSet/Set would duplicate existing CNCF functionality and add development and maintenance overhead.

## Additional Context
• Moving the health check mechanism to a dedicated custom resource better maintains the single responsibility principle.
• Teams managing health check and failover logic lifecycles can work independently from teams managing and operating the actual clusters.
• Continuing to leverage KeptnMetric and other CNCF building blocks ensures flexibility for future extensions while avoiding reinventing the wheel.
